// Package  implements the Azure ARM  service API version v3.
//
// The Bot Connector REST API allows your bot to send and receive messages to channels configured in the
// [Bot Framework Developer Portal](https://dev.botframework.com). The Connector service uses industry-standard REST
// and JSON over HTTPS.
//
// Client libraries for this REST API are available. See below for a list.
//
// Many bots will use both the Bot Connector REST API and the associated [Bot State REST API](/en-us/restapi/state).
// The
// Bot State REST API allows a bot to store and retrieve state associated with users and conversations.
//
// Authentication for both the Bot Connector and Bot State REST APIs is accomplished with JWT Bearer tokens, and is
// described in detail in the [Connector Authentication](/en-us/restapi/authentication) document.
//
// # Client Libraries for the Bot Connector REST API
//
// * [Bot Builder for C#](/en-us/csharp/builder/sdkreference/)
// * [Bot Builder for Node.js](/en-us/node/builder/overview/)
// * Generate your own from the [Connector API Swagger
// file](https://raw.githubusercontent.com/Microsoft/BotBuilder/master/CSharp/Library/Microsoft.Bot.Connector.Shared/Swagger/ConnectorAPI.json)
//
// © 2016 Microsoft
package schema


// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "github.com/Azure/go-autorest/autorest"
)

const (
// DefaultBaseURI is the default URI used for the service
DefaultBaseURI = "https://api.botframework.com")

// BaseClient is the base client for .
type BaseClient struct {
    autorest.Client
    BaseURI string
}

// New creates an instance of the BaseClient client.
func New()BaseClient {
    return NewWithBaseURI(DefaultBaseURI, )
}

// NewWithBaseURI creates an instance of the BaseClient client.
func NewWithBaseURI(baseURI string, ) BaseClient {
    return BaseClient{
        Client: autorest.NewClientWithUserAgent(UserAgent()),
        BaseURI: baseURI,
    }
}

